### ISSUE TITLE
Исправить информацию в разделе Experiences 

### ISSUE THREAD

**Issue by jarinka-u** [jarinka-u/online-cv#1]
@izubkov 
1. открыть резюме Ухова Ирина (https://jarinka-u.github.io/online-cv/)
2. в разделе Experiences исправить года работы в должности Customer Success Manager  на 2010-2020
3. в разделе Experiences исправить наименование должности Методист на Methodist 
4. в разделе Experiences по должности Методист исправить наименование организации с РТУ МИРЭА, Москва  на MGOU, Moscow

**Comment by izubkov** [comment]
fixed: d0c04bf

**Comment by izubkov** [comment]
fixed: d0c04bf
